services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/target/
    ports:
      - 8000:8000
    env_file:
      - .env
      - .env.local
    environment:
      - MY_LOG_LEVEL=info
      - MY_LOG_STYLE=Always
    command: "cargo watch -x run"
    depends_on:
    - mongodb
    - mongo-express

  mongodb:
    image: mongo:latest
    container_name: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo-data:/data/db
    logging:
      driver: none
      
  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: mongo
    depends_on:
      - mongodb

volumes:
  mongo-data:
    driver: local