@hostname = localhost:8000

POST http://{{hostname}}/account
Content-Type: application/json

{
    "username": "testuser01",
    "password": "1234abc",
    "email": "testuser@example.com",
    "info": {
        "display_name": "testuser_name",
        "display_img": "https://www.muitsfriday.dev/static/ebed7bd5537c02b401aa83c75bb04786/3faea/doge.webp"
    }
}